title: Hongry Github Pages
show_downloads: false
email: hongry18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    hongry log
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hongry.io" # the base hostname & protocol for your site
facebook_username: hongry18
github_username:  hongry18

paginate: 5

remote_theme: "dracula/gh-pages"
show_header: true

excerpt_separator: <!--more-->

sass:
    style: compressed

# Build settings
markdown: kramdown

gems: [
  jekyll-gist
  ,jekyll-paginate
]
